### ISSUE TITLE
Toggle from dark to light (and reverse) for plots

### ISSUE THREAD

**Issue by gabrielparriaux** [juba/bookup-html#3]
Dear @juba,

Thanks a lot for the great Quarto format! It’s just so much exactly what I needed! 

I’m considering using `bookup-html+dark` which gives the ability to switch from dark to light. 

Would it be possible to also switch between dark and light plots at the same time? Maybe using something like Mickaël Canouil is doing here: https://mickael.canouil.fr/posts/2023-05-30-quarto-light-dark/?

Or if it’s too complicated, would you have some recommendation about a ggplot theme that would fit for both light and dark mode? I see in your live example that the plots are light, but no so “aggressively” light in the dark rendered page. Did you use an existing theme or some custom one?

Thanks a lot for helping!

**Comment by juba** [comment]
Hi,

I don't think there is anything special in my sample files, it is just the base ggplot2 theme.

Maybe a way to have both light and dark figures could be to generate them in SVG and then use CSS to style them, but I'm not sure it would work with ggplot2. Or you can try to implement the solution given by Mickaël Canouil directly in your document.

**Comment by gabrielparriaux** [comment]
Hello,

Thanks a lot for your answer! I might try to implement the solution of Mickaël in the future.
