### ISSUE TITLE
`code-line-numbers` doesn't working

### ISSUE THREAD

**Issue by noau** [juba/bookup-html#5]
Thanks for your great and beautiful template! I'm using this template writing some tutorials, but I found that the `code-line-numbers` option seems not to work. Whether I add it to the attribute of code blocks or to `_quarto.yml` under `bookup-html`, it doesn't works. And sometimes the left side(the area line numers are expected) will just disappear. Am I using the wrong way, or is there's any way to fix it? Thanks.

**Comment by juba** [comment]
Hi,

I think this should now be fixed. Can you confirm it ?

Thanks for taking the time to report the issue.
