### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by yves-amevoin** [juba/bookup-html#6]
Thanks for your extensions! I use it a lot. 

Seems like there is an issue with check boxes. 

Here is a minimal example.

**bookup-html**
```
---
title: "Fichier test"
format: bookup-html
toc: true
lang: "fr-FR"
---



- [x] 0ne
- [ ] Two
- [x] Three
```

![image](https://github.com/user-attachments/assets/374abee8-3dd4-48c5-912f-0d4154d3b4c4)

---

**html**

```
---
title: "Fichier test"
format: html
toc: true
lang: "fr-FR"
---



- [x] 0ne
- [ ] Two
- [x] Three
```

![image](https://github.com/user-attachments/assets/4fb4817c-49dd-4ddb-9667-7806cb3925a8)

**Comment by juba** [comment]
Hi,

I think the issue should now be fixed. I'm closing it now but don't hesitate to reopen it if you still have the problem.

Thanks for the detailed report and the reproducible example.
